layout_spectrum: 0.32115175388753414
typography_spectrum: 0.6220049031544477
color:
  brandStrength: 0.6405061832629144
  lightness: 0.43893686146475375
  saturation: 0.16211897041648626
  rhythmicContrast: 0.9528026194311678
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
name: Stitch the net
author:
  name: Bj√∏rn Otto Vasbotten
  url: stitch.no
